jQuery(function(){var JCART=(function(){function updateExternal(){var subtotal=jQuery('#jcart-subtotal').text().replace("Rp ",""),berat=jQuery('#jcart-berat').text(),itemCount=jQuery('#jcart-qty').text(),itemCount=jQuery.trim(itemCount);jQuery('#external-subtotal').text(subtotal);jQuery('#external-berat').text(berat);jQuery('#external-jumlah').text(itemCount);jQuery('#totalbelanja,#totalbelanja2,#total').val(subtotal.replace(/\./g,""));jQuery('#beratbelanja').val(berat);jQuery('#totalpcs').val(itemCount);jQuery('.texttotalbelanja,.texttotal').text(subtotal?subtotal:'0');jQuery('.textberat').text(berat?berat:'0');jQuery('.textqty').text(itemCount);}
updateExternal();var path=templateDirectory+'/oketoko/inc/jcart',container=jQuery('#jcart'),token=jQuery('[name=jcartToken]').val(),tip=jQuery('#jcart-tooltip'),sizetip=jQuery('#jcart-sizetip');var config=(function(){var config=null;jQuery.ajax({url:path+'/config-loader.php',data:{"ajax":"true"},dataType:'json',async:false,success:function(response){config=response;},error:function(){alert('Ajax error: Edit the path in jcart.js to fix.');}});return config;}());var setup=(function(){if(config.tooltip===true){}
jQuery('#jcart-buttons').remove();jQuery.ajaxSetup({type:'POST',url:path+'/relay.php',success:function(response){container.html(response);jQuery('#jcart-buttons').remove();updateExternal();},error:function(x,e){var s=x.status,m='Ajax error: ';if(s===0){m+='Check your network connection.';}
if(s===404||s===500){m+=s;}
if(e==='parsererror'||e==='timeout'){m+=e;}
alert(m);}});}());var isCheckout=jQuery('#jcart-is-checkout').val();function add(form){var itemQty=form.find('[name='+config.item.qty+']'),itemPrice=form.find('[name='+config.item.price+']'),itemAdd=form.find('[name='+config.item.add+']');jQuery.ajax({data:form.serialize()+'&'+config.item.add+'='+itemAdd.val(),success:function(response){if(itemPrice.val()==''&&sizetip.css('display')=='none'){sizetip.fadeIn('20').delay('1500').fadeOut('20');}else if(itemPrice.val()>0&&tip.css('display')=='none'){tip.fadeIn('20');}
container.html(response);jQuery('#jcart-buttons').remove();updateExternal();}});}
function update(input){var updateId=input.parent().find('[name="jcartItemId[]"]').val();var newQty=input.val();if(newQty){var updateTimer=window.setTimeout(function(){jQuery.ajax({data:{"jcartUpdate":1,"itemId":updateId,"itemQty":newQty,"jcartIsCheckout":isCheckout,"jcartToken":token}});},1000);}
input.keydown(function(e){if(e.which!==9){window.clearTimeout(updateTimer);}});}
function remove(link){var queryString=link.attr('href');queryString=queryString.split('=');var removeId=queryString[1];jQuery.ajax({type:'GET',data:{"jcartRemove":removeId,"jcartIsCheckout":isCheckout}});}
jQuery('.jcart').submit(function(e){add(jQuery(this));e.preventDefault();});container.keydown(function(e){if(e.which===13){e.preventDefault();}});container.delegate('[name="jcartItemQty[]"]','keyup',function(){update(jQuery(this));$(".coupon,.kurir,#pilihankurir").val(''),$("#diskon,#ongkir").val('0'),getTotalHarga(),$(".voucher,.bdisc,#resultongkir").slideUp(),$(".voucherinfo").slideDown();});container.delegate('.jcart-remove','click',function(e){remove(jQuery(this));e.preventDefault();$(".coupon,.kurir,#pilihankurir").val(''),$("#diskon,#ongkir").val('0'),getTotalHarga(),$(".voucher,.bdisc,#resultongkir").slideUp(),$(".voucherinfo").slideDown();});}());});